# Generated by Django 3.2.9 on 2022-07-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersOfPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(default='test@gmail.com', max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('message', models.CharField(default='Hello I like your portfolio', max_length=500)),
            ],
        ),
    ]
