# Generated by Django 3.2.9 on 2022-07-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_subcatgeory_item_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=255)),
                ('question_body', models.CharField(max_length=1000)),
                ('tags', models.CharField(max_length=500)),
            ],
        ),
    ]
