# Generated by Django 3.2.9 on 2022-07-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_questions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_body',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='tags',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
